#ifndef MULTICOLOR_LED_ID_H_
#define MULTICOLOR_LED_ID_H_

enum MULTICOLOR_LED{
	LED_AW_OFF                                     = 0x0,
	LED_AW_ON                                      = 0x1,
	LED_MESSAGE                                    = 0x2,
	LED_TEST                                       = 0x3,
	LED_CALL                                       = 0x4,
	LED_GAME_SLOW                                  = 0x5,
	LED_GAME_NORMAL                                = 0x6,
	LED_GAME_FAST                                  = 0x7,
	LED_CHARGE_0_25PERCENT                         = 0x8,
	LED_CHARGE_26_50PERCENT                        = 0x9,
	LED_CHARGE_51_75PERCENT                        = 0xa,
	LED_CHARGE_76_100PERCENT                       = 0xb,
	LED_CHARGE_100PERCENT                          = 0xc,
	LED_SKYLINE_SLOW                               = 0xd,
	LED_SKYLINE_NORMAL                             = 0xe,
	LED_SKYLINE_FAST                               = 0xf,
	LED_RIBBON_SLOW                                = 0x10,
	LED_RIBBON_NORMAL                              = 0x11,
	LED_RIBBON_FAST                                = 0x12,
	LED_FLOWER_SLOW                                = 0x13,
	LED_FLOWER_NORMAL                              = 0x14,
	LED_FLOWER_FAST                                = 0x15,
	LED_WAVE_SLOW                                  = 0x16,
	LED_WAVE_NORMAL                                = 0x17,
	LED_WAVE_FAST                                  = 0x18,
	LED_GAME_AUDIO_SKYLINE                         = 0x19,
	LED_GAME_AUDIO_FLOWER                          = 0x1a,
	LED_GAME_AUDIO_SINGLE_COLOR_RED                = 0x1b,
	LED_GAME_AUDIO_SINGLE_COLOR_GREEN              = 0x1c,
	LED_GAME_AUDIO_SINGLE_COLOR_BLUE               = 0x1d,
	LED_GAME_AUDIO_SINGLE_COLOR_YELLOW             = 0x1e,
	LED_GAME_AUDIO_SINGLE_COLOR_PURPLE             = 0x1f,
	LED_GAME_AUDIO_SINGLE_COLOR_CYAN               = 0x20,
	LED_GAME_AUDIO_SINGLE_COLOR_WHITE              = 0x21,
	LED_GAME_AUDIO_GUN                             = 0x22,
	LED_AUDIO_RANDOM                               = 0x23,
	LED_AUDIO_SPEED                                = 0x24,
	LED_AUDIO_POINT                                = 0x25,
	LED_BILLIARDS_FAST                             = 0x26,
	LED_BILLIARDS_NORMAL                           = 0x27,
	LED_BILLIARDS_SLOW                             = 0x28,
	LED_COLOR_COLLISION                            = 0x29,
	LED_COMET                                      = 0x2a,
	LED_COMET_BACKCOLOR                            = 0x2b,
	LED_NEWTON_BALL                                = 0x2c,
	LED_SEESAW                                     = 0x2d,
	LED_SEESAW_BACKCOLOR                           = 0x2e,
	LED_SWING                                      = 0x2f,
	LED_SWING_BACKCOLOR                            = 0x30,
	LED_WATER_WAVE                                 = 0x31,
	LED_WATER_WAVE_BACKCOLOR                       = 0x32,
	LED_NUBIA_INTER                                = 0x34,
	LED_COLOR_NUBIA_FLOW                           = 0x35,
	LED_AUDIO_SINGLE_DIRECTION                     = 0x36,
	LED_BOOT_MODE                                  = 0x37,
	LED_MEDIA_USER_DEFINED_SAVE                    = 0x3b,
	LED_ALERM_USER_DEFINED_SAVE                    = 0x3c,
	LED_CALLING_USER_DEFINED_SAVE                  = 0x3d,
	LED_GAME_USER_DEFINED_PREVIEW                  = 0x3e,
	LED_GAME_USER_DEFINED_SAVE                     = 0x3f
};

#endif