#
# Makefile for the nubia drivers.
#
obj-$(CONFIG_NUBIA_TOUCH)                     += touch/
obj-$(CONFIG_NUBIA_SENSORS)                   += sensors/
obj-$(CONFIG_NUBIA_FINGERPRINT)               += fingerprint/
obj-$(CONFIG_NUBIA_MULTICOLORLIGHT)           += multicolor-led/
obj-$(CONFIG_NUBIA_CYPRESS_KEYBOARD_GAMEFIRE) += cy8c4014l_touchkey/
obj-$(CONFIG_NUBIA_USB_CC_CTRL)               += cc_control/
obj-$(CONFIG_NUBIA_SENSORS_SENS)              += sensors_sensitivity/